language: python
python:
  - "3.5"
  - "3.4"
install:
    - pip install -r requirements.txt
cache: pip
before_script:
  - export PYTHONPATH=`pwd`
script: "nosetests --with-coverage --cover-package=app"